var subjectDetails = {
        "Matrices and Calculus": ["Matrices", "Eigen Values and Eigen Vectors", "Single Variable Calculus", "Multivariable Calculus", "Multiple Integrals"],
        "Advanced Engineering Physics": ["Crystallography & Materials Characterization", "Quantum Mechanics", "Quantum Computing", "Magnetic and Dielectric Materials", "Laser and Fibre Optics"],
        "Programming for Problem Solving": ["Overview of C and Selection Structures", "Repetition, Loop Statements and Arrays", "Functions and Pointers", "Strings and User Defined Data Types", "File Handling, Searching and Sorting"],
        "Basic Electrical Engineering": ["D.C. Circuits", "A.C. Circuits", "Transformers", "Electrical Machines", "Electrical Installations"],
        "Computer Aided Engineering Drawing": ["Introduction to Engineering Graphics", "Orthographic Projections", "Projections of Regular Solids", "Development of Surfaces", "Isometric Projections"],
        "Engineering Chemistry": ["Water and Its Treatment", "Electrochemistry and Corrosion", "Energy Sources", "Polymers", "Advanced Functional Materials"],
        "English for Skill Enhancement": ["Perspectives", "Digital Transformation", "Attitude and Gratitude", "Entrepreneurship", "Integrity and Professionalism"],
        "Ordinary Differential Equations and Vector Calculus": ["First Order ODEs", "Higher Order ODEs", "Laplace Transforms", "Vector Differentiation", "Vector Integration"],
        "Data Structures": ["Introduction, Linear Lists, Stacks, Queues", "Trees, Binary Search Trees", "Multi-way Search Trees, Heaps", "Graphs, Sorting Algorithms", "Hashing and Collision Resolution"],
        "Electronic Devices and Applications": ["P-N Junction Diode Characteristics", "Applications of P-N Junction Diode", "Bipolar Junction Transistor and UJT", "Field-Effect Transistor and MOSFET", "Special Purpose Diodes"],
        "Mathematical and Statistical Foundations": ["Random Variables and Probability", "Continuous Distributions and Sampling", "Estimation", "Tests of Hypotheses", "Stochastic Processes and Markov Chains"],
        "Computer Organization and Architecture": ["Boolean Algebra and Logic Gates", "Combinational Logic", "Register Transfer and Micro-operations", "Microprogrammed Control", "I/O and Memory Organization"],
        "Object Oriented Programming through Java": ["OOP Concepts and Java Basics", "Inheritance, Packages and Interfaces", "Exception Handling and Multithreading", "Collections and Java I/O", "Java Networking and JDBC"],
        "Software Engineering": ["Introduction to Software Engineering", "Requirements Engineering", "Design Engineering", "Testing Strategies", "Risk and Quality Management"],
        "Database Management System": ["Database Concepts, ER Model", "Relational Model", "SQL: Queries, Constraints, Triggers", "Transaction Management, Concurrency", "Indexing and File Organization"],
        "Web Technologies": ["HTML5, CSS3, JavaScript", "Server-side Programming", "PHP/Node.js and Databases", "Web Frameworks", "Web Services and APIs"],
        "Discrete Mathematics": ["Mathematical Logic", "Set Theory", "Algebraic Structures", "Elementary Combinatorics", "Graph Theory"],
        "Operating Systems": ["OS Introduction and Structures", "CPU Scheduling, System Models", "Process Synchronization, Deadlocks", "Memory Management, Virtual Memory", "File System Interface and Operations"],
        "Algorithms Design and Analysis": ["Algorithm Analysis, Divide and Conquer", "Disjoint Sets, Heaps, Backtracking", "Dynamic Programming", "Greedy Method, Graph Algorithms", "Branch and Bound, NP-Completeness"],
        "Computer Networks": ["Internet, Protocols, Network Core", "Application Layer, HTTP, DNS", "Transport Layer, TCP, UDP", "Network Layer, Routing", "Link Layer, Error Detection"],
        "Artificial Intelligence": ["Introduction to AI, Problem Solving", "Search Strategies", "Knowledge Representation", "Planning and Acting", "Learning and Expert Systems"],
        "Innovation and Entrepreneurship": ["Foundations of Innovation", "Problem and Customer Identification", "Opportunity Assessment and Prototyping", "Business and Financial Models", "Startups and IPR"],
        "Machine Learning": ["Introduction to ML, Model Performance", "Feature Engineering, PCA, SVD", "Supervised Learning, Regression", "Unsupervised Learning, Clustering", "Ensemble Methods, Neural Networks"],
        "Automata and Compiler Design": ["Finite Automata and Regular Languages", "Context-Free Grammars", "Pushdown Automata", "Lexical Analysis and Parsing", "Code Generation and Optimization"],
        "Natural Language Processing": ["Text Processing and Morphology", "Language Models, N-grams", "Syntax and Parsing", "Semantics and Word Sense", "Machine Translation, Summarization"],
        "Generative AI": ["Introduction to Generative Models", "Variational Autoencoders", "Generative Adversarial Networks", "Transformer Architecture", "Large Language Models and Applications"],
        "Deep Learning": ["Neural Network Fundamentals", "Convolutional Neural Networks", "Recurrent Neural Networks, LSTM", "Attention Mechanisms, Transformers", "Advanced Architectures, GANs"],
        "Reinforcement Learning": ["MDP and Bellman Equations", "Dynamic Programming Methods", "Monte Carlo Methods", "Temporal Difference Learning", "Deep Reinforcement Learning"],
        "Data Analytics and Visualization": ["Introduction to Data Analytics", "Data Preprocessing and Cleaning", "Exploratory Data Analysis", "Statistical Analysis and Modeling", "Visualization Tools and Dashboards"],
        "Mathematical Foundations of Computer Science": ["Propositional and Predicate Logic", "Sets, Relations and Functions", "Graph Theory and Trees", "Algebraic Structures", "Lattices and Boolean Algebra"],
        "Advanced Data Structures": ["Amortized Analysis, Splay Trees", "Red-Black Trees, Skip Lists", "Tries, Suffix Trees", "B-Trees, External Sorting", "Advanced Hashing Techniques"],
        "Advanced Algorithms": ["Approximation Algorithms", "Randomized Algorithms", "Linear Programming", "Network Flow Algorithms", "Computational Geometry"],
        "Advanced Computer Architecture": ["Pipelining and ILP", "Memory Hierarchy Design", "Multiprocessor Systems", "Interconnection Networks", "GPU Architecture"]
      };