import urllib.request, os

base = 'c:/mlr/homepage/departments/images'

depts = {
    'cse': [
        ('ajmeera-kiran', 'https://mlrit.ac.in/wp-content/uploads/2022/03/kiran-1.jpg'),
        ('k-srinivas-rao', 'https://mlrit.ac.in/wp-content/uploads/2022/02/K.Srinivas-Rao.jpg'),
        ('n-sirisha', 'https://mlrit.ac.in/wp-content/uploads/2022/03/Dr.-N-Shirisha-e1688636559185.jpg'),
        ('a-balaram', 'https://mlrit.ac.in/wp-content/uploads/2022/02/it-fac-3.jpg'),
        ('v-thrimurthulu', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Dr-Thrimoorthulu-Sir-Pic.jpg'),
        ('k-venkata-subbaiah', 'https://mlrit.ac.in/wp-content/uploads/2025/10/kvs2.jpg'),
        ('kandrakunta-chinnaiah', 'https://mlrit.ac.in/wp-content/uploads/2025/03/Chinniaha-Sir-Profile-Pic.jpg'),
        ('j-mahalakshmi', 'https://mlrit.ac.in/wp-content/uploads/2025/02/Mahalakshmi_prof_pic.jpeg'),
        ('john-samuel-babu', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Dr-John-Sir.jpg'),
        ('k-gagan-kumar', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Gagan-Kumar-Koduru-Passport-Size-Photo.jpg'),
        ('sai-krishna', 'https://mlrit.ac.in/wp-content/uploads/2023/07/20201004205350316-e1688980840523.jpg'),
        ('nagarjuna-tandra', 'https://mlrit.ac.in/wp-content/uploads/2023/07/Nagarjuna-Passport-photo.jpg'),
        ('b-sanjai-prasad', 'https://mlrit.ac.in/wp-content/uploads/2023/01/sajay-e1688980925489.jpg'),
        ('michael-preetam', 'https://mlrit.ac.in/wp-content/uploads/2023/01/michael.jpg'),
        ('t-venkata-nagaraju', 'https://mlrit.ac.in/wp-content/uploads/2022/06/nagaraju.jpeg'),
        ('m-kalpana-chowdary', 'https://mlrit.ac.in/wp-content/uploads/2022/06/Dr-Kalpana-e1688980538965.jpg'),
        ('b-devananda-rao', 'https://mlrit.ac.in/wp-content/uploads/2022/03/deva.jpg'),
        ('k-pushpa-rani', 'https://mlrit.ac.in/wp-content/uploads/2022/03/pushpa.jpg'),
        ('g-prabhakara-reddy', 'https://mlrit.ac.in/wp-content/uploads/2022/03/prabhakar.jpg'),
        ('m-srinivasa-rao', 'https://mlrit.ac.in/wp-content/uploads/2022/03/srunu.jpg'),
        ('allam-sangeetha', 'https://mlrit.ac.in/wp-content/uploads/2022/03/sangeetha.jpg'),
        ('guduru-durga-bhavani', 'https://mlrit.ac.in/wp-content/uploads/2026/01/Durga-Bhavani-Web-Profile-pic-1.jpeg'),
        ('shaik-mohammed-ilias', 'https://mlrit.ac.in/wp-content/uploads/2026/01/Ilias-Website-Profile-pic.jpeg'),
        ('sasmita-pradhan', 'https://mlrit.ac.in/wp-content/uploads/2026/01/Sasmita-Pradhan_pic.png'),
        ('b-muralikrishna', 'https://mlrit.ac.in/wp-content/uploads/2026/01/B-MURALI-KRISHNA-PROFILE-Pic-Website.jpeg'),
        ('b-ratnamala', 'https://mlrit.ac.in/wp-content/uploads/2025/10/WhatsApp-Image-2025-09-27-at-17.27.42.jpeg'),
        ('j-chaitanya', 'https://mlrit.ac.in/wp-content/uploads/2025/03/J.-Chaitanya-Profile-Pic.jpeg'),
        ('d-jeevitha', 'https://mlrit.ac.in/wp-content/uploads/2025/03/D-Jeevitha-Profile-Pic.jpeg'),
        ('d-tejaswini', 'https://mlrit.ac.in/wp-content/uploads/2025/02/Tejaswini-Madam.jpg'),
        ('hareesh-pesala', 'https://mlrit.ac.in/wp-content/uploads/2025/02/Harish-CSE-Faculty.jpg'),
        ('ramya-s-pure', 'https://mlrit.ac.in/wp-content/uploads/2025/01/Ramya-madam-profile-pic.jpg'),
        ('p-santhosh-kumar', 'https://mlrit.ac.in/wp-content/uploads/2025/01/Santhosh_Photo-scaled.jpeg'),
        ('jetti-sri-lakshmi', 'https://mlrit.ac.in/wp-content/uploads/2024/08/IMG-20240926-WA0006.jpg'),
        ('ms-sabitha', 'https://mlrit.ac.in/wp-content/uploads/2024/08/Sabita-Profile-Pic.jpg'),
        ('a-laxmi-prasanna', 'https://mlrit.ac.in/wp-content/uploads/2024/08/IMG-20240926-WA0007.jpg'),
        ('kshitiza-vasudeva', 'https://mlrit.ac.in/wp-content/uploads/2024/08/PHOTO-2024-05-06-16-14-13.jpg'),
        ('boddu-srilatha', 'https://mlrit.ac.in/wp-content/uploads/2024/08/Srilatha-10.37.50-e1722577040984.jpg'),
        ('v-balakrishna-reddy', 'https://mlrit.ac.in/wp-content/uploads/2024/05/IMG-20240919-WA0009.jpg'),
        ('p-victor-emmanuel', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Victor-Emma.jpg'),
        ('m-vineesha', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Vineesha-Madam.jpg'),
        ('b-manjusha', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Manjusha-e1722581998707.jpg'),
        ('m-srinivasulu', 'https://mlrit.ac.in/wp-content/uploads/2024/05/Mrs-Srinivasulu-e1722581382285.jpg'),
        ('nagarjuna-rao-gudelli', 'https://mlrit.ac.in/wp-content/uploads/2023/07/NAG.jpg'),
        ('swathi', 'https://mlrit.ac.in/wp-content/uploads/2023/07/WhatsApp-Image-2023-07-04-at-1.21.15-PM.jpeg'),
        ('k-samatha', 'https://mlrit.ac.in/wp-content/uploads/2023/04/samatha-e1688980189966.jpeg'),
        ('a-nagamani', 'https://mlrit.ac.in/wp-content/uploads/2023/04/IMG-20220808-WA0028-e1688980659498.jpg'),
        ('kranthi-kumari', 'https://mlrit.ac.in/wp-content/uploads/2023/04/photo.jpg'),
        ('ragini-patil', 'https://mlrit.ac.in/wp-content/uploads/2023/01/ragini-e1688980432482.jpg'),
        ('lingaiah-suramsetti', 'https://mlrit.ac.in/wp-content/uploads/2023/01/lingaiah.png'),
        ('i-sapthami', 'https://mlrit.ac.in/wp-content/uploads/2022/07/Sapthami.jpg'),
        ('p-deepak', 'https://mlrit.ac.in/wp-content/uploads/2022/06/Deepak-photo-new-e1688980759957.jpg'),
        ('jeethu-philip', 'https://mlrit.ac.in/wp-content/uploads/2022/03/jeethu.jpg'),
        ('j-pradeep-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/pradeep.jpg'),
        ('telise-vinod', 'https://mlrit.ac.in/wp-content/uploads/2022/03/vinod.jpg'),
        ('kukunoor-shekar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/sekhar.jpg'),
        ('g-praveen', 'https://mlrit.ac.in/wp-content/uploads/2022/03/IMG1630815428840.jpg'),
        ('sk-lokesh-naik', 'https://mlrit.ac.in/wp-content/uploads/2022/03/nayak.jpg'),
        ('oruganti-ramesh', 'https://mlrit.ac.in/wp-content/uploads/2022/03/ramesh.jpg'),
        ('divya-priya-degala', 'https://mlrit.ac.in/wp-content/uploads/2022/03/Divya-Priya-madam.jpg'),
        ('palelli-purushotham', 'https://mlrit.ac.in/wp-content/uploads/2022/03/WhatsApp-Image-2025-09-26-at-15.49.47.jpeg'),
        ('bashetty-suman', 'https://mlrit.ac.in/wp-content/uploads/2022/03/suman.jpg'),
        ('b-veda-vidhya', 'https://mlrit.ac.in/wp-content/uploads/2022/03/IMG-20230618-WA0002-e1688633968659.jpg'),
        ('k-swetha', 'https://mlrit.ac.in/wp-content/uploads/2022/03/swetha.jpg'),
        ('en-vijaya-kumari', 'https://mlrit.ac.in/wp-content/uploads/2022/02/ds-fac-1.jpg'),
    ],
    'eee': [
        ('ashok-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/ashok.jpg'),
        ('dileep-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/dilip.jpg'),
        ('sumana-das', 'https://mlrit.ac.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-06-at-10.28.58-AM.jpeg'),
        ('bv-rajanna', 'https://mlrit.ac.in/wp-content/uploads/2023/07/PHOTO-2023-07-06-11-56-37-1.jpg'),
        ('t-bhargava-ramu', 'https://mlrit.ac.in/wp-content/uploads/2022/03/bhargav.jpg'),
        ('sonu-kumar', 'https://mlrit.ac.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-06-at-3.18.33-PM.jpeg'),
        ('y-lalitha-kameswari', 'https://mlrit.ac.in/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-06-at-10.13.29-AM.jpeg'),
        ('t-mrudula', 'https://mlrit.ac.in/wp-content/uploads/2023/07/PHOTO-2023-07-06-11-56-18.jpg'),
        ('n-karthik', 'https://mlrit.ac.in/wp-content/uploads/2022/03/karthik.jpg'),
        ('p-jithendar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/jithendra.jpg'),
        ('a-yadagiri', 'https://mlrit.ac.in/wp-content/uploads/2022/03/yadagiri.jpg'),
        ('k-rajasri', 'https://mlrit.ac.in/wp-content/uploads/2022/03/rajasri.jpg'),
        ('a-shubhangi-rao', 'https://mlrit.ac.in/wp-content/uploads/2022/02/eee-fac-5.jpg'),
        ('ch-srivardhan-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/02/IMG-20231008-WA0052.jpg'),
        ('m-sreenivasa-reddy', 'https://mlrit.ac.in/wp-content/uploads/2022/02/eee-fac-2.jpg'),
    ],
    'mechanical': [
        ('krishnaraj', 'https://mlrit.ac.in/wp-content/uploads/2022/03/krishna.jpg'),
        ('prabhu-kishore', 'https://mlrit.ac.in/wp-content/uploads/2022/03/Prabhu-kishore.jpeg'),
        ('ravi-kiran', 'https://mlrit.ac.in/wp-content/uploads/2022/03/ravi11.jpg'),
        ('harikishor', 'https://mlrit.ac.in/wp-content/uploads/2022/03/hari-1.jpg'),
        ('k-limbadri', 'https://mlrit.ac.in/wp-content/uploads/2022/03/limbdri.jpg'),
        ('pramod-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/pramodh.jpg'),
        ('lokasani-bhanuprakash', 'https://mlrit.ac.in/wp-content/uploads/2022/03/lokesh.jpg'),
        ('alli-anil-kumar', 'https://mlrit.ac.in/wp-content/uploads/2026/04/Anil-Kumar.jpg'),
        ('laxmi', 'https://mlrit.ac.in/wp-content/uploads/2024/01/Laxmi.jpg'),
        ('chintala-muralikrishna', 'https://mlrit.ac.in/wp-content/uploads/2022/03/chmuirali.jpg'),
        ('j-sunil-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/sunil.jpg'),
        ('j-laxmi-prasad', 'https://mlrit.ac.in/wp-content/uploads/2022/03/jlp.jpg'),
        ('ne-chandra-prasad', 'https://mlrit.ac.in/wp-content/uploads/2022/03/prasad.jpg'),
        ('mudhuganti-mahender', 'https://mlrit.ac.in/wp-content/uploads/2022/03/mahendra.jpg'),
        ('g-chandramohana-reddy', 'https://mlrit.ac.in/wp-content/uploads/2022/03/chandra-1.jpg'),
        ('m-sundeep', 'https://mlrit.ac.in/wp-content/uploads/2022/03/sandeep11.jpg'),
        ('s-nagaraju', 'https://mlrit.ac.in/wp-content/uploads/2022/03/NAGARAJU-1.jpg'),
        ('g-anandarao', 'https://mlrit.ac.in/wp-content/uploads/2022/03/anand-1.jpg'),
        ('g-venkata-rambabu', 'https://mlrit.ac.in/wp-content/uploads/2022/03/rambabu.jpg'),
        ('m-venkateswar-reddy', 'https://mlrit.ac.in/wp-content/uploads/2022/03/venkat.jpg'),
    ],
    'aeronautical': [
        ('satyanarayana', 'https://mlrit.ac.in/wp-content/uploads/2022/02/aer-fac-1.jpg'),
        ('vivek-anand', 'https://mlrit.ac.in/wp-content/uploads/2022/02/aer-fac-2.jpg'),
        ('veeranjaneyulu', 'https://mlrit.ac.in/wp-content/uploads/2022/03/anji.jpg'),
        ('arvind-singh', 'https://mlrit.ac.in/wp-content/uploads/2025/09/Arvind-singh.jpg'),
        ('s-jayalakshmi', 'https://mlrit.ac.in/wp-content/uploads/2025/09/Jayalakshmi.jpg'),
        ('thangavel-sanjeeviraja', 'https://mlrit.ac.in/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-09-at-11.15.54.jpeg'),
        ('nayani-uday-ranjan', 'https://mlrit.ac.in/wp-content/uploads/2022/03/ranjan.jpg'),
        ('swetha-bala', 'https://mlrit.ac.in/wp-content/uploads/2022/03/swetha-1.jpg'),
        ('saiprakash', 'https://mlrit.ac.in/wp-content/uploads/2022/03/sai.jpg'),
        ('m-ganesh', 'https://mlrit.ac.in/wp-content/uploads/2022/03/ganesh.jpg'),
        ('yelamasetti-balram', 'https://mlrit.ac.in/wp-content/uploads/2026/01/balaram-photo.jpg'),
        ('sreekanth-sura', 'https://mlrit.ac.in/wp-content/uploads/2022/03/sura.jpg'),
        ('g-sravanthi', 'https://mlrit.ac.in/wp-content/uploads/2022/03/Sravanthi.jpeg'),
        ('b-manideep', 'https://mlrit.ac.in/wp-content/uploads/2022/03/mani.jpg'),
        ('nirmith-kumar-mishra', 'https://mlrit.ac.in/wp-content/uploads/2022/03/mishra.jpg'),
        ('a-udaya-deepika', 'https://mlrit.ac.in/wp-content/uploads/2022/03/eepika.jpg'),
        ('k-arun-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/arun.jpg'),
        ('b-nagaraj-goud', 'https://mlrit.ac.in/wp-content/uploads/2022/03/nagaraj.jpg'),
        ('a-sai-kumar', 'https://mlrit.ac.in/wp-content/uploads/2022/03/saikumar.jpg'),
    ],
    'mba': [
        ('ramanjaneyulu', 'https://mlrit.ac.in/wp-content/uploads/2025/08/MBA-HOD-e1754126571871.jpeg'),
        ('narasimha-rao', 'https://mlrit.ac.in/wp-content/uploads/2022/02/mba-fac.jpg'),
        ('aruna', 'https://mlrit.ac.in/wp-content/uploads/2022/03/aruna-1.jpg'),
        ('umrez', 'https://mlrit.ac.in/wp-content/uploads/2022/03/umrez.jpg'),
        ('m-tirupalaiah', 'https://mlrit.ac.in/wp-content/uploads/2022/03/tirupalai.jpg'),
        ('jostna-kumar', 'https://mlrit.ac.in/wp-content/uploads/2025/08/MBA-Faculty.jpg'),
        ('vasudha-kurikala', 'https://mlrit.ac.in/wp-content/uploads/2025/08/Copy-of-My-Image-e1754372578835.jpg'),
        ('a-koti-reddy', 'https://mlrit.ac.in/wp-content/uploads/2022/03/koti.jpg'),
        ('m-parsharamulu', 'https://mlrit.ac.in/wp-content/uploads/2022/03/parasuram.jpg'),
        ('bs-venkat-narayana', 'https://mlrit.ac.in/wp-content/uploads/2022/03/vn.jpg'),
        ('b-vishnu-prasad', 'https://mlrit.ac.in/wp-content/uploads/2024/05/VISHNU-PHOTO.jpg'),
        ('k-rajya-lakshmi', 'https://mlrit.ac.in/wp-content/uploads/2024/05/IMG-20240507-WA0004.jpg'),
        ('sudha-rani', 'https://mlrit.ac.in/wp-content/uploads/2024/05/sudha-rani.jpeg'),
        ('n-madhusudhanarao', 'https://mlrit.ac.in/wp-content/uploads/2022/03/madhu.jpg'),
        ('ram-narsa-goud', 'https://mlrit.ac.in/wp-content/uploads/2024/05/1715064950497.jpg'),
    ],
}

for dept, fac_list in depts.items():
    os.makedirs(f'{base}/{dept}', exist_ok=True)
    ok = 0
    fail = 0
    for fname, url in fac_list:
        ext = url.rsplit('.', 1)[-1][:4]
        path = f'{base}/{dept}/{fname}.{ext}'
        if os.path.exists(path):
            ok += 1
            continue
        try:
            urllib.request.urlretrieve(url, path)
            ok += 1
        except Exception as e:
            fail += 1
            print(f'  FAIL {dept}/{fname}: {e}')
    print(f'{dept}: {ok} ok, {fail} fail (total {len(fac_list)})')
